name: deploy
on:
  push:
    branches:
      - master
    paths-ignore:   # 变更不触发部署
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:   # 变更不触发部署
      - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
            SOURCE: "lib/"
            REMOTE_HOST: ${{ secrets.SSH_HOST }}
            REMOTE_USER: ${{ secrets.SSH_USERNAME }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: start
        run: npm start
